<?php

/**
 * @file
 * Contains asset.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function asset_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the asset module.
    case 'help.page.asset':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Asset include example') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_element_info_alter().
 */
function asset_element_info_alter(array &$info)
{
    if (isset($info['table'])) {
        $info['table']['#attached']['library'][] = 'asset/asset.css';
    }
}


function asset_block_view_system_powered_by_block_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block) {

    $build['#attached']['library'][] = 'asset/asset.js';
}
